// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKHVxZhl8eoiNx5QUd4dwPQIRVn70MFSQ',
    appId: '1:352385596252:web:b6d24065c1d98ff8c45f99',
    messagingSenderId: '352385596252',
    projectId: 'financeapp-33146',
    authDomain: 'financeapp-33146.firebaseapp.com',
    storageBucket: 'financeapp-33146.firebasestorage.app',
    measurementId: 'G-6K8T7TES62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpr7CI6Ao7_d6u7hq-Vpg0qZ7Bihuz4DY',
    appId: '1:352385596252:android:954291a89e0ce11cc45f99',
    messagingSenderId: '352385596252',
    projectId: 'financeapp-33146',
    storageBucket: 'financeapp-33146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3poKwFLD9UhmvPiQpeEOznoF72pROlQY',
    appId: '1:352385596252:ios:a39a5b955ee9930cc45f99',
    messagingSenderId: '352385596252',
    projectId: 'financeapp-33146',
    storageBucket: 'financeapp-33146.firebasestorage.app',
    iosClientId: '352385596252-qu5fc732rn94sn4s0pjb2bls0lttgsoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3poKwFLD9UhmvPiQpeEOznoF72pROlQY',
    appId: '1:352385596252:ios:a39a5b955ee9930cc45f99',
    messagingSenderId: '352385596252',
    projectId: 'financeapp-33146',
    storageBucket: 'financeapp-33146.firebasestorage.app',
    iosClientId: '352385596252-qu5fc732rn94sn4s0pjb2bls0lttgsoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKHVxZhl8eoiNx5QUd4dwPQIRVn70MFSQ',
    appId: '1:352385596252:web:8d73a8d175221c77c45f99',
    messagingSenderId: '352385596252',
    projectId: 'financeapp-33146',
    authDomain: 'financeapp-33146.firebaseapp.com',
    storageBucket: 'financeapp-33146.firebasestorage.app',
    measurementId: 'G-MM61037VQL',
  );
}